core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'


urlpatterns = [
    path('my-recipes/', views.my_recipes, name='my_recipes'),
]

recipe/urls.py
from django.urls import path

from . import views

app_name = 'recipe'


urlpatterns = [
    path('', views.recipes, name='recipes'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('new/', views.new, name='new'),
]

recipe_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('recipe/', include('recipe.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

recipe/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    ingredients = models.TextField()
    steps = models.TextField()
    image = models.ImageField(upload_to='recipe_images', blank=True, null=True)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Repeat your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

recipe/forms.py
from django import forms

from .models import Recipe


INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class NewRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'ingredients', 'steps', 'image', 'category']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'ingredients': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'steps': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'ingredients', 'steps', 'category']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'ingredients': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'steps': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }

core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm

from recipe.models import Recipe, Category


def home(request):
    recipes = Recipe.objects.all()
    categories = Category.objects.all()
    return render(request, 'core/home.html', {
        'recipes': recipes,
        'categories': categories
    })


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')

    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from recipe.models import Recipe


@login_required
def my_recipes(request):
    recipes = Recipe.objects.filter(created_by=request.user)

    return render(request, 'dashboard/myrecipes.html', {
        'recipes': recipes
    })

recipe/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Recipe, Category
from .forms import NewRecipeForm, EditRecipeForm


def recipes(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0) 
    categories = Category.objects.all()
    recipes = Recipe.objects.filter()

    if category_id:
        recipes = recipes.filter(category_id=category_id)

    if query:
        recipes = recipes.filter(Q(name__icontains=query) | Q(ingredients__icontains=query))

    return render(request, 'recipe/recipes.html', {
        'categories': categories,
        'recipes': recipes
    })


def detail(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    related_recipes = Recipe.objects.filter(category=recipe.category).exclude(pk=pk)[:3]

    return render(request, 'recipe/detail.html', {
        'recipe': recipe,
        'related_recipes': related_recipes
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewRecipeForm(request.POST, request.FILES)

        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.created_by = request.user
            recipe.save()

            return redirect('recipe:detail', pk=recipe.id)

        
    else:
        form = NewRecipeForm()

        return render(request, 'recipe/form.html', {
            'form': form,
            'title': 'New Recipe'
        })
    

@login_required
def delete(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk, created_by=request.user)

    recipe.delete()

    return redirect('dashboard:my_recipes')


@login_required
def edit(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    print(request)
    if request.method == "POST":
        print("inside if")
        form = EditRecipeForm(request.POST, instance=recipe)

        if form.is_valid():
            form.save()

            return redirect('recipe:detail', pk=recipe.id)

    else:
        form = EditRecipeForm(instance=recipe)

        return render(request, 'recipe/form.html', {
            'form': form,
            'title': 'Edit Recipe'
        })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Recipe App</title>
</head>

<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-bold text-purple-600 hover:text-indigo-500">Recipe App</a>

        <div class="space-x-6">
            <a href="{% url 'recipe:recipes' %}" class="text-lg font-semibold hover:text-gray-500">Browse Recipes</a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'recipe:new' %}" class="text-lg font-semibold hover:text-gray-500">New Recipe</a>
            <a href="{% url 'dashboard:my_recipes' %}" class="text-lg font-semibold hover:text-gray-500">Dashboard</a>
            <a href="{% url 'core:logout' %}"
                class="px-6 py-3 text-lg font-semibold bg-red-300 text-white rounded-xl hover:bg-red-400">LogOut</a>
            {% else %}
            <a href="{% url 'core:signup' %}"
                class="px-6 py-3 text-lg font-semibold bg-pink-500 text-white rounded-xl hover:bg-teal-700">Sign
                Up</a>
            <a href="{% url 'core:login' %}"
                class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">New Recipes</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for recipe in recipes %}
        <div>
            <a href="{% url 'recipe:detail' recipe.id %}">
                <div>
                    <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ recipe.name }}</h2>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="#">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ category.name }}</h2>
                    <p class="text-gray-500">{{ category.items.count }} items</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log In</h1>

    <form method="POST" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br />
            {{ form.username }}
        </div <div class="mb-3">
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br />
            {{ form.password }}
        </div>

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            Submit
        </button>
    </form>
</div>

{% if form.errors or form.non_field_errors %}
<div class="mb-3 p-6 bg-red-100 rounded-xl">
    {% for field in form %}
    {{ field.errors }}
    {% endfor %}
</div>
{% endif %}
</form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="POST" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br />
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br />
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br />
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label><br />
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            Submit
        </button>
    </form>
</div>
{% endblock %}

dashboard/templates/dashboard/myrecipes.html
{% extends 'core/base.html' %}

{% block title %}My Recipes{% endblock %}


{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">My Recipes</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for recipe in recipes %}
        <div>
            <a href="{% url 'recipe:detail' recipe.id %}">
                <div>
                    <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ recipe.name }}</h2>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

recipe/templates/recipe/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}


{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">My Recipes</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for recipe in recipes %}
        <div>
            <a href="{% url 'recipe:detail' recipe.id %}">
                <div>
                    <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ recipe.name }}</h2>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

recipe/templates/recipe/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ recipe.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ recipe.name }}</h1>
        <p class="text-gray-500"><strong>By: {{ recipe.created_by.username }}</strong></p>

        <p class="test-gray-700">
            <strong class="text-gray500">Ingredients:</strong>
            <br />
            {{ recipe.ingredients }}
        </p>

        <p class="test-gray-700">
            <strong class="text-gray500">Steps:</strong>
            <br />
            {{ recipe.steps }}
        </p>

        {% if request.user == recipe.created_by %}
        <a href="{% url 'recipe:edit' recipe.id %}"
            class="inline-block mt-6 mx-3 px-6 py-3 text-lg font-semibold bg-green-700 text-white rounded-xl">Edit</a>
        <a href="{% url 'recipe:delete' recipe.id %}"
            class="inline-block mt-6 mx-3 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
        {% endif %}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Recipes</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for recipe in related_recipes %}
        <div>
            <a href="{% url 'recipe:detail' recipe.id %}">
                <div>
                    <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ recipe.name }}</h2>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

recipe/templates/recipe/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}
    </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
        Submit
    </button>
</form>
{% endblock %}

recipe/templates/recipe/new.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
        {{ field.errors }}
        {% endfor %}
    </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
        Submit
    </button>
</form>
{% endblock %}

recipe/templates/recipe/recipes.html
{% extends 'core/base.html' %}

{% block title %}Browse{% endblock %}


{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4">
    <div class="col-span-1">
        <form method="get" action="{% url 'recipe:recipes' %}">
            <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}"
                placeholder="Search">

            <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
        </form>

        <hr class="my-6">
        <p class="font-semibold">Categories</p>
        <ul>
            {% for category in categories %}
            <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
                <a href="{% url 'recipe:recipes' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
            </li>
            {% endfor %}
        </ul>

        <hr class="my-6">
        <p class="font-semibold">Clear Filters</p>
        <ul>
            <li><a href="{% url 'recipe:recipes' %}"
                    class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
        </ul>
    </div>

    <div class="col-span-3">
        <div class="grid grid-cols-3 gap-3">
            {% for recipe in recipes %}
            <div>
                <a href="{% url 'recipe:detail' recipe.id %}">
                    <div>
                        <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ recipe.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}